if(WIN32)
    find_package(CURL CONFIG REQUIRED)
elseif(ANDROID)
    set(QV2RAY_ANDROID_LIB_PREFIX "${CMAKE_SOURCE_DIR}/libs/android")
    set(QV2RAY_ANDROID_ARCH_PREFIX "${QV2RAY_ANDROID_LIB_PREFIX}/${CMAKE_ANDROID_ARCH_ABI}")
    set(CURL_INCLUDE_DIRS "${QV2RAY_ANDROID_ARCH_PREFIX}/include")
    set(CURL_LIBRARIES "-L${QV2RAY_ANDROID_ARCH_PREFIX}/lib -lcurl -lz -lssl -lcrypto -lc")
else()
    find_package(CURL REQUIRED)
endif()
